apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-api
  labels:
    app: read-api
spec:
  selector:
    matchLabels:
      app: read-api
  template:
    metadata:
      annotations:
        prometheus.io/port: "3000"
        prometheus.io/scrape: "true"
      labels:
        app: read-api
    spec:
      containers:
        - name: read-api
          image: 782141671658.dkr.ecr.us-east-1.amazonaws.com/test/read-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128M"
            limits:
              cpu: "300m"
              memory: "256M"
          envFrom:
            - configMapRef:
                name: read-api-env
          env:
            - name: ELASTIC_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-certs
                  key: tls.crt
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-credentials
                  key: username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-credentials
                  key: password
