apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-api
  labels:
    app: read-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: read-api
  template:
    metadata:
      annotations:
        prometheus.io/port: "3000"
        prometheus.io/scrape: "true"
      labels:
        app: read-api
    spec:
      containers:
        - name: read-api
          image: localhost:32000/read-api:registry
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: read-api-env
          env:
            - name: ELASTIC_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-certs
                  key: tls.crt
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-credentials
                  key: username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-credentials
                  key: password
