apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: read-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: read-api
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
