---
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "hard"

# Shrink default JVM heap.
esJavaOpts: "-Xmx1024m -Xms1024m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "3500m"
    memory: "2Gi"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "gp2"
  resources:
    requests:
      storage: 20Gi
