grafana:
  additionalDataSources:
    - name: loki
      type: loki
      url: http://loki.observability.svc.cluster.local:3100
    - name: tempo
      type: tempo
      url: http://tempo.observability.svc.cluster.local:3100
kubeControllerManager:
  endpoints:
    - 192.168.3.53
kubeScheduler:
  endpoints:
    - 192.168.3.53
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: kubernetes-service-endpoints
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          # annotation 'prometheus.io/scrape' must be set to 'true'
          - action: keep
            regex: true
            source_labels:
              [__meta_kubernetes_service_annotation_prometheus_io_scrape]

          # allow override of http scheme
          - action: replace
            regex: (https?)
            source_labels:
              [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            target_label: __scheme__

          # allow override of default /metrics path
          - action: replace
            regex: (.+)
            source_labels:
              [__meta_kubernetes_service_annotation_prometheus_io_path]
            target_label: __metrics_path__

          # allow override of default port
          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels:
              [
                __address__,
                __meta_kubernetes_service_annotation_prometheus_io_port,
              ]
            target_label: __address__
          - { action: labelmap, regex: __meta_kubernetes_service_label_(.+) }
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_service_name]
            target_label: name

      - job_name: kubernetes-pod-endpoints
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # annotation 'prometheus.io/scrape' must be set to 'true'
          - action: keep
            regex: true
            source_labels:
              [__meta_kubernetes_pod_annotation_prometheus_io_scrape]

          # allow override of http scheme
          - action: replace
            regex: (https?)
            source_labels:
              [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
            target_label: __scheme__

          # allow override of default /metrics path
          - action: replace
            regex: (.+)
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            target_label: __metrics_path__

          # allow override of default port
          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels:
              [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            target_label: __address__
          - { action: labelmap, regex: __meta_kubernetes_pod_label_(.+) }
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: name
